[package]
name = "polypad-db"
description = "Database connections, schema introspection and SQL execution for PolyPad."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]

[lints]
workspace = true
