import { mockIPC } from "@tauri-apps/api/mocks";
import { render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";

import type { AppInfo } from "../../shared/ipc";
import { AppShell } from "./AppShell";

const APP_INFO: AppInfo = {
  name: "PolyPad",
  version: "9.9.9",
  protocolVersion: "1.0",
  os: "windows",
  arch: "x86_64",
};

function mockAppInfo() {
  mockIPC((command) => {
    if (command === "app_info") return APP_INFO;
    throw new Error(`unexpected command: ${command}`);
  });
}

describe("AppShell", () => {
  it("lays out the regions of the main window", () => {
    mockAppInfo();
    render(<AppShell />);

    expect(screen.getByRole("navigation", { name: "Application menu" })).toBeInTheDocument();
    expect(screen.getByRole("complementary", { name: "Explorer" })).toBeInTheDocument();
    expect(screen.getByRole("main")).toBeInTheDocument();
    expect(screen.getByRole("region", { name: "Code editor" })).toBeInTheDocument();
    expect(screen.getByRole("region", { name: "Results" })).toBeInTheDocument();
    expect(screen.getByRole("contentinfo", { name: "Status" })).toBeInTheDocument();
  });

  it("shows the version reported by the Rust side", async () => {
    mockAppInfo();
    render(<AppShell />);

    expect(await screen.findByText("PolyPad 9.9.9")).toBeInTheDocument();
  });

  it("says so when the version cannot be read", async () => {
    const consoleError = vi.spyOn(console, "error").mockImplementation(() => undefined);
    mockIPC(() => {
      throw new Error("IPC unavailable");
    });
    render(<AppShell />);

    expect(await screen.findByText("Version unavailable")).toBeInTheDocument();
    expect(consoleError).toHaveBeenCalledOnce();
  });

  it("re-tints the workspace and resets the mode when the language changes", async () => {
    mockAppInfo();
    const user = userEvent.setup();
    const { container } = render(<AppShell />);

    const workspace = container.firstElementChild;
    expect(workspace).toHaveAttribute("data-language", "csharp");

    await user.selectOptions(screen.getByLabelText("Language"), "python");

    expect(workspace).toHaveAttribute("data-language", "python");
    expect(screen.getByLabelText("Mode")).toHaveValue("script");
    const status = screen.getByRole("contentinfo");
    expect(within(status).getByText("Python")).toBeInTheDocument();
    expect(within(status).getByText("Script")).toBeInTheDocument();
  });

  it("switches result tabs with the arrow keys", async () => {
    mockAppInfo();
    const user = userEvent.setup();
    render(<AppShell />);

    const results = within(screen.getByRole("region", { name: "Results" }));
    await user.click(results.getByRole("tab", { name: "Results" }));
    await user.keyboard("{ArrowRight}");

    const sqlTab = results.getByRole("tab", { name: "SQL" });
    expect(sqlTab).toHaveAttribute("aria-selected", "true");
    expect(sqlTab).toHaveFocus();
    expect(results.getByRole("tabpanel")).toHaveTextContent(
      "SQL generated by your script appears here.",
    );

    await user.keyboard("{End}");
    expect(results.getByRole("tab", { name: "Log" })).toHaveFocus();
    await user.keyboard("{ArrowRight}");
    expect(results.getByRole("tab", { name: "Results" })).toHaveFocus();
  });
});
