import js from "@eslint/js";
import prettier from "eslint-config-prettier";
import reactHooks from "eslint-plugin-react-hooks";
import { reactRefresh } from "eslint-plugin-react-refresh";
import { defineConfig, globalIgnores } from "eslint/config";
import globals from "globals";
import tseslint from "typescript-eslint";

const IPC_ONLY_MESSAGE =
  "Talk to the Rust side only through the typed wrappers in src/shared/ipc (docs/adr/0002).";

export default defineConfig([
  // bindings.ts is generated by tauri-specta and checked for drift in CI instead of linted.
  globalIgnores(["dist", "coverage", "src/shared/ipc/bindings.ts"]),
  {
    files: ["**/*.{ts,tsx}"],
    extends: [
      js.configs.recommended,
      tseslint.configs.strictTypeChecked,
      tseslint.configs.stylisticTypeChecked,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite(),
    ],
    languageOptions: {
      globals: globals.browser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [{ name: "@tauri-apps/api", message: IPC_ONLY_MESSAGE }],
          patterns: [{ group: ["@tauri-apps/api/*"], message: IPC_ONLY_MESSAGE }],
        },
      ],
    },
  },
  {
    // The IPC layer is the single place allowed to import the Tauri JS API.
    files: ["src/shared/ipc/**/*.ts", "src/test/**/*.ts"],
    rules: { "no-restricted-imports": "off" },
  },
  {
    // Tests may additionally fake the IPC transport, but still call commands via the wrappers.
    files: ["src/**/*.test.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [{ name: "@tauri-apps/api", message: IPC_ONLY_MESSAGE }],
          patterns: [
            { group: ["@tauri-apps/api/*", "!@tauri-apps/api/mocks"], message: IPC_ONLY_MESSAGE },
          ],
        },
      ],
    },
  },
  {
    files: ["**/*.js"],
    extends: [js.configs.recommended, tseslint.configs.disableTypeChecked],
    languageOptions: { globals: globals.node },
  },
  prettier,
]);
