// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Returns the build information of the running application. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
};

/* Types */
/**  Static facts about the running build, shown in the status bar. */
export type AppInfo = {
	/**  Product name. */
	name: string,
	/**  Application version (`Cargo.toml`). */
	version: string,
	/**  Kernel protocol version this build speaks. */
	protocolVersion: string,
	/**  Operating system family, e.g. `windows`, `macos`, `linux`. */
	os: string,
	/**  CPU architecture, e.g. `x86_64`, `aarch64`. */
	arch: string,
};

/**
 *  Error returned by fallible commands.
 * 
 *  Serialized as `{ "code": "internal", "reference": "…" }`. It never carries internal paths,
 *  secrets or user code: the full cause is written to the log under the same `reference`, so
 *  what the user sees can be matched to a log entry without leaking details over IPC.
 */
export type CommandError = 
/**  An unexpected failure. The cause is logged, never sent. */
{ code: "internal"; 
/**  Correlates this response with the log entry that holds the cause. */
reference: string };

