// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Returns the build information of the running application. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**
	 *  Preferences, scripts tree and recovered tabs in one call at start-up.
	 * 
	 *  # Errors
	 * 
	 *  Only `internal`: a missing folder or journal is reported inside the snapshot.
	 */
	workspaceSnapshot: () => typedError<WorkspaceSnapshot_Serialize, CommandError>(__TAURI_INVOKE("workspace_snapshot")),
	/**
	 *  Records the unsaved state of a buffer.
	 * 
	 *  # Errors
	 * 
	 *  `recoveryUnavailable` when the journal cannot be written.
	 */
	journalBuffer: (bufferId: BufferId, snapshot: BufferSnapshot_Deserialize) => typedError<null, CommandError>(__TAURI_INVOKE("journal_buffer", { bufferId, snapshot })),
	/**
	 *  Forgets a buffer's unsaved state (saved, reverted or closed).
	 * 
	 *  # Errors
	 * 
	 *  `recoveryUnavailable` when the journal cannot be written.
	 */
	discardBuffer: (bufferId: BufferId) => typedError<null, CommandError>(__TAURI_INVOKE("discard_buffer", { bufferId })),
	/**
	 *  Records the open tabs.
	 * 
	 *  # Errors
	 * 
	 *  `recoveryUnavailable` when the journal cannot be written.
	 */
	setSession: (session: Session) => typedError<null, CommandError>(__TAURI_INVOKE("set_session", { session })),
	/**  The UI has flushed its pending journal writes after `FlushRequested`; close the window. */
	readyToClose: () => __TAURI_INVOKE<void>("ready_to_close"),
	/**
	 *  Lists the scripts folder.
	 * 
	 *  # Errors
	 * 
	 *  `scriptsFolderUnavailable` when the folder is gone or unreadable.
	 */
	listScripts: () => typedError<ScriptTree, CommandError>(__TAURI_INVOKE("list_scripts")),
	/**
	 *  Reads a script.
	 * 
	 *  # Errors
	 * 
	 *  `notFound`, `notAScript`, `unsupportedDocument` or `outsideScriptsFolder`.
	 */
	openScript: (path: ScriptPath) => typedError<LoadedScript_Serialize, CommandError>(__TAURI_INVOKE("open_script", { path })),
	/**
	 *  Stamp of a script on disk, or `null` when it does not exist.
	 * 
	 *  # Errors
	 * 
	 *  `notAScript` or `outsideScriptsFolder`.
	 */
	scriptStatus: (path: ScriptPath) => typedError<string | null, CommandError>(__TAURI_INVOKE("script_status", { path })),
	/**
	 *  Saves a script if the disk still holds `expected` (`null`: no file).
	 * 
	 *  # Errors
	 * 
	 *  `conflict` when the disk changed (the file is left untouched), `notFound` when its folder
	 *  is gone, `notAScript` or `outsideScriptsFolder`.
	 */
	saveScript: (path: ScriptPath, document: Document_Deserialize, expected: string | null) => typedError<ContentStamp, CommandError>(__TAURI_INVOKE("save_script", { path, document, expected })),
	/**
	 *  Creates a script in `parent` (the root when `null`).
	 * 
	 *  # Errors
	 * 
	 *  `invalidName`, `alreadyExists`, `notAScript` (the name lacks `.ppad`), `notFound` or
	 *  `notAFolder` for `parent`.
	 */
	createScript: (parent: string | null, name: string, document: Document_Deserialize) => typedError<CreatedScript, CommandError>(__TAURI_INVOKE("create_script", { parent, name, document })),
	/**
	 *  Creates a folder in `parent` (the root when `null`).
	 * 
	 *  # Errors
	 * 
	 *  `invalidName`, `alreadyExists`, `notFound` or `notAFolder` for `parent`.
	 */
	createFolder: (parent: string | null, name: string) => typedError<ScriptPath, CommandError>(__TAURI_INVOKE("create_folder", { parent, name })),
	/**
	 *  Renames a script or folder in place.
	 * 
	 *  # Errors
	 * 
	 *  `invalidName`, `alreadyExists`, `notFound` or `notAScript` (a script would lose `.ppad`).
	 */
	renameEntry: (path: ScriptPath, name: string) => typedError<ScriptPath, CommandError>(__TAURI_INVOKE("rename_entry", { path, name })),
	/**
	 *  Moves a script or folder into `folder` (the root when `null`).
	 * 
	 *  # Errors
	 * 
	 *  `moveIntoItself`, `alreadyExists`, `notFound` or `notAFolder`.
	 */
	moveEntry: (path: ScriptPath, folder: string | null) => typedError<ScriptPath, CommandError>(__TAURI_INVOKE("move_entry", { path, folder })),
	/**
	 *  Moves a script or folder to the operating system's trash.
	 * 
	 *  # Errors
	 * 
	 *  `notFound`, `outsideScriptsFolder`, or `internal` when the trash refuses it.
	 */
	deleteEntry: (path: ScriptPath) => typedError<null, CommandError>(__TAURI_INVOKE("delete_entry", { path })),
	/**
	 *  Lets the user pick another scripts folder; `null` when the dialog was cancelled.
	 * 
	 *  The UI must not call this while scripts of the current folder have unsaved changes.
	 * 
	 *  # Errors
	 * 
	 *  `scriptsFolderUnavailable` when the chosen folder cannot be used.
	 */
	chooseScriptsFolder: (title: string) => typedError<{
	/**  Folder name, empty for a volume root (never the full path, which stays in Rust). */
	name: string,
	/**  Its contents. */
	tree: ScriptTree,
} | null, CommandError>(__TAURI_INVOKE("choose_scripts_folder", { title })),
	/**
	 *  Replaces the UI preferences and saves them.
	 * 
	 *  # Errors
	 * 
	 *  `internal` when the preferences file cannot be written; the change still applies for this
	 *  session.
	 */
	updatePreferences: (preferences: UiPreferences) => typedError<null, CommandError>(__TAURI_INVOKE("update_preferences", { preferences })),
};

/** Events */
export const events = {
	flushRequested: makeEvent<FlushRequested>("flush-requested"),
	scriptsChanged: makeEvent<ScriptsChanged>("scripts-changed"),
};

/* Constants */
export const LANGUAGE_MODES = [{"language":"csharp","modes":["statements","expression","program"]},{"language":"fsharp","modes":["script","expression"]},{"language":"java","modes":["statements","expression","program"]},{"language":"kotlin","modes":["script"]},{"language":"go","modes":["statements","program"]},{"language":"typescript","modes":["statements","expression","module"]},{"language":"javascript","modes":["statements","expression","module"]},{"language":"python","modes":["script","expression"]},{"language":"rust","modes":["statements"]},{"language":"sql","modes":["sql"]}] as const;

/* Types */
/**  Static facts about the running build, shown in the status bar. */
export type AppInfo = {
	/**  Product name. */
	name: string,
	/**  Application version (`Cargo.toml`). */
	version: string,
	/**  Kernel protocol version this build speaks. */
	protocolVersion: string,
	/**  Operating system family, e.g. `windows`, `macos`, `linux`. */
	os: string,
	/**  CPU architecture, e.g. `x86_64`, `aarch64`. */
	arch: string,
};

/**
 *  Identifier of an editor buffer; also the name of its snapshot file, hence the strict
 *  alphabet (ASCII letters, digits and `-`).
 */
export type BufferId = string;

/**  Unsaved state of one buffer. */
export type BufferSnapshot = BufferSnapshot_Serialize | BufferSnapshot_Deserialize;

/**  Unsaved state of one buffer. */
export type BufferSnapshot_Deserialize = {
	/**  The script it edits; `None` for an untitled script. */
	path: ScriptPath | null,
	/**  Stamp of the file when the buffer last matched it; `None` if it never existed. */
	baseStamp: ContentStamp | null,
	/**  The unsaved document. */
	document: Document_Deserialize,
	/**  When the snapshot was taken, in milliseconds since the Unix epoch. */
	updatedAt: number | null,
};

/**  Unsaved state of one buffer. */
export type BufferSnapshot_Serialize = {
	/**  The script it edits; `None` for an untitled script. */
	path: ScriptPath | null,
	/**  Stamp of the file when the buffer last matched it; `None` if it never existed. */
	baseStamp: ContentStamp | null,
	/**  The unsaved document. */
	document: Document_Serialize,
	/**  When the snapshot was taken, in milliseconds since the Unix epoch. */
	updatedAt: number | null,
};

/**
 *  Error returned by fallible commands.
 * 
 *  Serialized with a `code` tag, for example `{ "code": "conflict", "path": "a.ppad", … }`. It
 *  never carries absolute paths, secrets or user code: expected failures carry only data the UI
 *  sent (script paths relative to the scripts folder) or fixed reason codes, and anything
 *  unexpected becomes `internal`, whose cause is logged under the same `reference`.
 */
export type CommandError = 
/**  An unexpected failure. The cause is logged, never sent. */
{ code: "internal"; 
/**  Correlates this response with the log entry that holds the cause. */
reference: string } | 
/**  The script or folder does not exist. */
{ code: "notFound"; 
/**  The entry. */
path: ScriptPath } | 
/**  An entry with that path already exists. */
{ code: "alreadyExists"; 
/**  The entry. */
path: ScriptPath } | 
/**  The script changed on disk since the caller read it. */
{ code: "conflict"; 
/**  The script. */
path: ScriptPath; 
/**  Stamp of what is on disk now; `null` when the file is gone. */
current: ContentStamp | null } | 
/**  A name typed by the user breaks a naming rule. */
{ code: "invalidName"; 
/**  The rule it breaks. */
problem: NameError } | 
/**  The entry is not a script. */
{ code: "notAScript"; 
/**  The entry. */
path: ScriptPath } | 
/**  The entry is not a folder. */
{ code: "notAFolder"; 
/**  The entry. */
path: ScriptPath } | 
/**  A folder cannot move into itself or one of its subfolders. */
{ code: "moveIntoItself"; 
/**  The folder. */
path: ScriptPath } | 
/**  The entry resolves outside the scripts folder (a link pointing elsewhere). */
{ code: "outsideScriptsFolder"; 
/**  The entry. */
path: ScriptPath } | 
/**  The file is not a script this build can open. */
{ code: "unsupportedDocument"; 
/**  The file. */
path: ScriptPath; 
/**  Why. */
problem: DocumentProblem } | 
/**  The document is too large to be saved as a script (it could not be reopened). */
{ code: "documentTooLarge"; 
/**  The script. */
path: ScriptPath } | 
/**  The operating system trash refused the entry (network drives often have none). */
{ code: "trashUnavailable"; 
/**  The entry. */
path: ScriptPath } | 
/**  No scripts folder could be opened; the user has to choose one. */
{ code: "scriptsFolderUnavailable" } | 
/**  The recovery journal cannot be written; editing works, crash recovery does not. */
{ code: "recoveryUnavailable" };

/**  Fingerprint of a script's bytes, used to notice changes made by other programs. */
export type ContentStamp = string;

/**  A script that was just created. */
export type CreatedScript = {
	/**  Where it was created. */
	path: ScriptPath,
	/**  Stamp of the written file. */
	stamp: ContentStamp,
};

/**  A script: its header and its code. */
export type Document = Document_Serialize | Document_Deserialize;

/**  Why a file cannot be opened as a script. */
export type DocumentProblem = 
/**  The file does not start with a JSON header. */
{ kind: "missingHeader" } | 
/**  The header is not valid JSON. */
{ kind: "invalidHeader"; 
/**  One-based line. */
line: number; 
/**  One-based column. */
column: number } | 
/**  No `---` line after the header. */
{ kind: "missingSeparator"; 
/**  One-based line where it was expected. */
line: number } | 
/**  The format version is missing or malformed. */
{ kind: "invalidVersion" } | 
/**  Written by a newer PolyPad. */
{ kind: "newerFormat" } | 
/**  The header names an unknown language. */
{ kind: "unknownLanguage" } | 
/**  The header names an unknown mode. */
{ kind: "unknownMode" } | 
/**  A header field has the wrong type. */
{ kind: "invalidField"; 
/**  The field. */
field: string } | 
/**  Larger than scripts may be. */
{ kind: "tooLarge" } | 
/**  Not UTF-8 text. */
{ kind: "invalidEncoding" } | 
/**  Another problem, described in the log. */
{ kind: "other" };

/**  A script: its header and its code. */
export type Document_Deserialize = {
	/**  Metadata stored before the separator. */
	header: Header_Deserialize,
	/**  Source code, exactly as written after the separator. */
	code: string,
	/**  Line ending used by the header and the separator. */
	newline: Newline,
};

/**  A script: its header and its code. */
export type Document_Serialize = {
	/**  Metadata stored before the separator. */
	header: Header_Serialize,
	/**  Source code, exactly as written after the separator. */
	code: string,
	/**  Line ending used by the header and the separator. */
	newline: Newline,
};

/**  How a kernel interprets a script. */
export type ExecutionMode = 
/**  A single expression whose value is dumped. */
"expression" | 
/**  A sequence of statements. */
"statements" | 
/**  A complete program with an entry point. */
"program" | 
/**  A script file in the language's own scripting dialect. */
"script" | 
/**  An ES module. */
"module" | 
/**  SQL statements. */
"sql";

/**  The window is closing: flush pending journal writes, then call `ready_to_close`. */
export type FlushRequested = null;

/**  Script metadata. */
export type Header = Header_Serialize | Header_Deserialize;

/**  Script metadata. */
export type Header_Deserialize = {
	/**  Language of the code. */
	language: Language,
	/**  How the kernel runs the code; always one of the language's modes. */
	mode: ExecutionMode,
	/**  Id of the database connection the script targets (Phase 4). */
	connection: string | null,
	/**  Packages the script references (Phase 7). */
	packages: PackageRef_Deserialize[],
	/**  Namespaces or modules imported implicitly. */
	imports: string[],
	/**  Header fields this build does not know, kept so that saving never drops them. */
	extra: string,
};

/**  Script metadata. */
export type Header_Serialize = {
	/**  Language of the code. */
	language: Language,
	/**  How the kernel runs the code; always one of the language's modes. */
	mode: ExecutionMode,
	/**  Id of the database connection the script targets (Phase 4). */
	connection: string | null,
	/**  Packages the script references (Phase 7). */
	packages: PackageRef_Serialize[],
	/**  Namespaces or modules imported implicitly. */
	imports: string[],
	/**  Header fields this build does not know, kept so that saving never drops them. */
	extra: string,
};

/**  A language a script can be written in. */
export type Language = 
/**  C#. */
"csharp" | 
/**  F#. */
"fsharp" | 
/**  Java. */
"java" | 
/**  Kotlin. */
"kotlin" | 
/**  Go. */
"go" | 
/**  TypeScript. */
"typescript" | 
/**  JavaScript. */
"javascript" | 
/**  Python. */
"python" | 
/**  Rust. */
"rust" | 
/**  SQL against the selected connection. */
"sql";

/**  A script read from disk. */
export type LoadedScript = LoadedScript_Serialize | LoadedScript_Deserialize;

/**  A script read from disk. */
export type LoadedScript_Deserialize = {
	/**  The script. */
	document: Document_Deserialize,
	/**  Loading upgraded or corrected the document, so it differs from the file. */
	normalized: boolean,
	/**  Stamp of the bytes on disk. */
	stamp: ContentStamp,
};

/**  A script read from disk. */
export type LoadedScript_Serialize = {
	/**  The script. */
	document: Document_Serialize,
	/**  Loading upgraded or corrected the document, so it differs from the file. */
	normalized: boolean,
	/**  Stamp of the bytes on disk. */
	stamp: ContentStamp,
};

/**
 *  Why a name or path is not acceptable.
 * 
 *  Serialized as `{ "kind": "invalidCharacter", "character": ":" }` so the UI can explain it.
 */
export type NameError = 
/**  The name, or a path component, is empty. */
{ kind: "empty" } | 
/**  The name exceeds [`MAX_NAME_BYTES`]. */
{ kind: "tooLong" } | 
/**  The name starts with a dot (hidden entries, `.` and `..`). */
{ kind: "leadingDot" } | 
/**  The name contains a character some platform forbids. */
{ kind: "invalidCharacter"; character: string } | 
/**  The name is a Windows device name such as `CON` or `LPT1`. */
{ kind: "reservedName" } | 
/**  The name ends with a dot or a space, which Windows strips. */
{ kind: "trailingDotOrSpace" };

/**  Line ending of the header and separator. */
export type Newline = 
/**  `\n`, used for new scripts. */
"lf" | 
/**  `\r\n`. */
"crlf";

/**  A package reference in the header. */
export type PackageRef = PackageRef_Serialize | PackageRef_Deserialize;

/**  A package reference in the header. */
export type PackageRef_Deserialize = {
	/**  Package id in its ecosystem. */
	name: string,
	/**  Requested version; `None` lets the resolver choose. */
	version: string | null,
	/**  Fields this build does not know. */
	extra: string,
};

/**  A package reference in the header. */
export type PackageRef_Serialize = {
	/**  Package id in its ecosystem. */
	name: string,
	/**  Requested version; `None` lets the resolver choose. */
	version: string | null,
	/**  Fields this build does not know. */
	extra: string,
};

/**  What the journal holds after a restart. */
export type RecoveredSession = RecoveredSession_Serialize | RecoveredSession_Deserialize;

/**  What the journal holds after a restart. */
export type RecoveredSession_Deserialize = {
	/**  Session tabs in order, then buffers the session did not list, oldest first. */
	tabs: RecoveredTab_Deserialize[],
	/**  The focused tab, if it was recovered. */
	active: BufferId | null,
};

/**  What the journal holds after a restart. */
export type RecoveredSession_Serialize = {
	/**  Session tabs in order, then buffers the session did not list, oldest first. */
	tabs: RecoveredTab_Serialize[],
	/**  The focused tab, if it was recovered. */
	active: BufferId | null,
};

/**  A tab to reopen. */
export type RecoveredTab = RecoveredTab_Serialize | RecoveredTab_Deserialize;

/**  A tab to reopen. */
export type RecoveredTab_Deserialize = {
	/**  The tab's buffer. */
	bufferId: BufferId,
	/**
	 *  The script it edits; `None` for an untitled script, or for work detached from a scripts
	 *  folder that is not open now.
	 */
	path: ScriptPath | null,
	/**
	 *  Set when the buffer edited this script in another scripts folder: it comes back untitled,
	 *  so it can only be saved under a new name, never over an unrelated file.
	 */
	previousPath: ScriptPath | null,
	/**  Unsaved changes; `None` when the tab was clean and should be reloaded from disk. */
	snapshot: BufferSnapshot_Deserialize | null,
};

/**  A tab to reopen. */
export type RecoveredTab_Serialize = {
	/**  The tab's buffer. */
	bufferId: BufferId,
	/**
	 *  The script it edits; `None` for an untitled script, or for work detached from a scripts
	 *  folder that is not open now.
	 */
	path: ScriptPath | null,
	/**
	 *  Set when the buffer edited this script in another scripts folder: it comes back untitled,
	 *  so it can only be saved under a new name, never over an unrelated file.
	 */
	previousPath: ScriptPath | null,
	/**  Unsaved changes; `None` when the tab was clean and should be reloaded from disk. */
	snapshot: BufferSnapshot_Serialize | null,
};

/**  An entry that moved within the root. */
export type Renamed = {
	/**  Previous location. */
	from: ScriptPath,
	/**  New location. */
	to: ScriptPath,
};

/**  What changed during one debounce window. */
export type ScriptChanges = {
	/**  Scripts and folders created, modified or deleted, sorted and without duplicates. */
	paths: ScriptPath[],
	/**  Entries renamed or moved within the root. */
	renamed: Renamed[],
	/**  Events were lost or cannot be attributed; everything must be re-read. */
	rescan: boolean,
};

/**
 *  A validated path of a script or folder inside the scripts root, such as
 *  `reports/orders.ppad`.
 */
export type ScriptPath = string;

/**  Folders and scripts under the scripts root. */
export type ScriptTree = {
	/**  Top-level entries, folders first, each group in natural order. */
	entries: TreeEntry[],
	/**  The walk stopped at the entry limit, so some entries are missing. */
	truncated: boolean,
};

/**  Other programs changed the scripts folder; re-read what the batch mentions. */
export type ScriptsChanged = ScriptChanges;

/**  The scripts folder as the explorer shows it. */
export type ScriptsFolder = {
	/**  Folder name, empty for a volume root (never the full path, which stays in Rust). */
	name: string,
	/**  Its contents. */
	tree: ScriptTree,
};

/**  Open tabs, in order. */
export type Session = {
	/**  Tabs from left to right. */
	tabs: SessionTab[],
	/**  The focused tab. */
	active: BufferId | null,
};

/**  A tab in the session. */
export type SessionTab = {
	/**  The tab's buffer. */
	bufferId: BufferId,
	/**  The script it edits; `None` for an untitled script. */
	path: ScriptPath | null,
};

/**  A folder or a script. */
export type TreeEntry = 
/**  A folder and its contents. */
{ kind: "folder"; 
/**  Location inside the root. */
path: ScriptPath; 
/**  Display name (the last path component). */
name: string; 
/**  Contents, ordered like the root. */
children: TreeEntry[] } | 
/**  A `.ppad` file. */
{ kind: "script"; 
/**  Location inside the root. */
path: ScriptPath; 
/**  Display name (the last path component). */
name: string };

/**  The part of the preferences the UI sees; it never includes file system paths. */
export type UiPreferences = {
	/**  Panel sizes (see [`Layout`]). */
	layout: { [key in string]: { [key in string]: number | null } },
	/**  Key binding overrides by command id; `None` unbinds the command. */
	keybindings: { [key in string]: string | null },
	/**  Language of the last script created, used for the next new script. */
	lastLanguage: Language | null,
};

/**  Everything the UI needs to draw its first frame. */
export type WorkspaceSnapshot = WorkspaceSnapshot_Serialize | WorkspaceSnapshot_Deserialize;

/**  Everything the UI needs to draw its first frame. */
export type WorkspaceSnapshot_Deserialize = {
	/**  UI preferences (layout, key bindings, last language). */
	preferences: UiPreferences,
	/**  The scripts folder; `null` when none could be opened and the user must choose one. */
	scriptsFolder: ScriptsFolder | null,
	/**  Tabs to reopen, with their unsaved changes. */
	session: RecoveredSession_Deserialize,
	/**  Whether unsaved changes are journaled; `false` means a crash would lose them. */
	recoveryAvailable: boolean,
	/**
	 *  Name of the chosen scripts folder when it could not be opened at start-up (an unplugged
	 *  drive, a moved folder); `scriptsFolder` is then the default folder, or `null`.
	 */
	unavailableFolder: string | null,
};

/**  Everything the UI needs to draw its first frame. */
export type WorkspaceSnapshot_Serialize = {
	/**  UI preferences (layout, key bindings, last language). */
	preferences: UiPreferences,
	/**  The scripts folder; `null` when none could be opened and the user must choose one. */
	scriptsFolder: ScriptsFolder | null,
	/**  Tabs to reopen, with their unsaved changes. */
	session: RecoveredSession_Serialize,
	/**  Whether unsaved changes are journaled; `false` means a crash would lose them. */
	recoveryAvailable: boolean,
	/**
	 *  Name of the chosen scripts folder when it could not be opened at start-up (an unplugged
	 *  drive, a moved folder); `scriptsFolder` is then the default folder, or `null`.
	 */
	unavailableFolder: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

