/**
 * The only gateway from the UI to the Rust side (enforced by ESLint, see docs/adr/0002).
 *
 * `bindings.ts` is generated by tauri-specta from the Rust command signatures; this module
 * re-exports the types and wraps each command in a function named after what it does. Every
 * wrapper resolves with the command's data or rejects with a {@link CommandFailure}.
 */
import {
  commands,
  events,
  LANGUAGE_MODES,
  type AppInfo,
  type BufferId,
  type BufferSnapshot_Serialize,
  type CommandError,
  type ContentStamp,
  type CreatedScript,
  type Document_Serialize,
  type DocumentProblem,
  type ExecutionMode,
  type Header_Serialize,
  type Language as LanguageId,
  type LoadedScript_Serialize,
  type NameError,
  type Newline,
  type RecoveredSession_Serialize,
  type RecoveredTab_Serialize,
  type ScriptChanges,
  type ScriptPath,
  type ScriptsFolder,
  type ScriptTree,
  type Session,
  type SessionTab,
  type TreeEntry,
  type UiPreferences,
  type WorkspaceSnapshot_Serialize,
} from "./bindings";

export type {
  AppInfo,
  BufferId,
  CommandError,
  ContentStamp,
  CreatedScript,
  DocumentProblem,
  ExecutionMode,
  LanguageId,
  NameError,
  Newline,
  ScriptChanges,
  ScriptPath,
  ScriptsFolder,
  ScriptTree,
  Session,
  SessionTab,
  TreeEntry,
  UiPreferences,
};
// The generated `_Serialize` and `_Deserialize` variants have the same shape.
export type Document = Document_Serialize;
export type Header = Header_Serialize;
export type LoadedScript = LoadedScript_Serialize;
export type BufferSnapshot = BufferSnapshot_Serialize;
export type RecoveredTab = RecoveredTab_Serialize;
export type RecoveredSession = RecoveredSession_Serialize;
export type WorkspaceSnapshot = WorkspaceSnapshot_Serialize;

/** Languages and the modes each offers (default first), as defined in Rust. */
export { LANGUAGE_MODES };

/** A command failed; `error` says why in terms the UI can act on. */
export class CommandFailure extends Error {
  readonly error: CommandError;

  constructor(error: CommandError, options?: ErrorOptions) {
    super(`command failed: ${error.code}`, options);
    this.name = "CommandFailure";
    this.error = error;
  }
}

type Outcome<T> = { status: "ok"; data: T } | { status: "error"; error: CommandError };

function isCommandError(value: unknown): value is CommandError {
  return (
    typeof value === "object" && value !== null && "code" in value && typeof value.code === "string"
  );
}

/**
 * Resolves with the data of a command. Rejections that are not a `CommandError` — the ACL
 * denying a command (sent as a string) or a broken transport — become `internal`.
 */
async function unwrap<T>(call: () => Promise<Outcome<T>>): Promise<T> {
  let outcome: Outcome<T>;
  try {
    outcome = await call();
  } catch (cause) {
    throw new CommandFailure({ code: "internal", reference: "transport" }, { cause });
  }
  if (outcome.status === "ok") {
    return outcome.data;
  }
  if (isCommandError(outcome.error)) {
    throw new CommandFailure(outcome.error);
  }
  throw new CommandFailure(
    { code: "internal", reference: "unrecognized" },
    { cause: outcome.error },
  );
}

/** Build information of the running application. */
export function getAppInfo(): Promise<AppInfo> {
  return commands.appInfo();
}

/** Preferences, scripts tree and recovered tabs, in one call at start-up. */
export function workspaceSnapshot(): Promise<WorkspaceSnapshot> {
  return unwrap(() => commands.workspaceSnapshot());
}

export function listScripts(): Promise<ScriptTree> {
  return unwrap(() => commands.listScripts());
}

export function openScript(path: ScriptPath): Promise<LoadedScript> {
  return unwrap(() => commands.openScript(path));
}

/** Stamp of a script on disk, or `null` when it does not exist. */
export function scriptStatus(path: ScriptPath): Promise<ContentStamp | null> {
  return unwrap(() => commands.scriptStatus(path));
}

/** Saves a script if the disk still holds `expected` (`null`: no file); returns the new stamp. */
export function saveScript(
  path: ScriptPath,
  document: Document,
  expected: ContentStamp | null,
): Promise<ContentStamp> {
  return unwrap(() => commands.saveScript(path, document, expected));
}

export function createScript(
  parent: ScriptPath | null,
  name: string,
  document: Document,
): Promise<CreatedScript> {
  return unwrap(() => commands.createScript(parent, name, document));
}

export function createFolder(parent: ScriptPath | null, name: string): Promise<ScriptPath> {
  return unwrap(() => commands.createFolder(parent, name));
}

export function renameEntry(path: ScriptPath, name: string): Promise<ScriptPath> {
  return unwrap(() => commands.renameEntry(path, name));
}

export function moveEntry(path: ScriptPath, folder: ScriptPath | null): Promise<ScriptPath> {
  return unwrap(() => commands.moveEntry(path, folder));
}

export function deleteEntry(path: ScriptPath): Promise<void> {
  return unwrap(() => commands.deleteEntry(path)).then(() => undefined);
}

/** Lets the user pick another scripts folder; `null` when the dialog was cancelled. */
export function chooseScriptsFolder(title: string): Promise<ScriptsFolder | null> {
  return unwrap(() => commands.chooseScriptsFolder(title));
}

export function journalBuffer(id: BufferId, snapshot: BufferSnapshot): Promise<void> {
  return unwrap(() => commands.journalBuffer(id, snapshot)).then(() => undefined);
}

export function discardBuffer(id: BufferId): Promise<void> {
  return unwrap(() => commands.discardBuffer(id)).then(() => undefined);
}

export function setSession(session: Session): Promise<void> {
  return unwrap(() => commands.setSession(session)).then(() => undefined);
}

export function updatePreferences(preferences: UiPreferences): Promise<void> {
  return unwrap(() => commands.updatePreferences(preferences)).then(() => undefined);
}

/** Tells the backend the journal is flushed after `FlushRequested`, so the window may close. */
export function readyToClose(): Promise<void> {
  return commands.readyToClose();
}

/** Calls `handler` for every batch of external changes; resolves with an unsubscribe function. */
export function onScriptsChanged(handler: (changes: ScriptChanges) => void): Promise<() => void> {
  return events.scriptsChanged.listen((event) => {
    handler(event.payload);
  });
}

/** Calls `handler` when the window is about to close and the journal must be flushed. */
export function onFlushRequested(handler: () => void): Promise<() => void> {
  return events.flushRequested.listen(() => {
    handler();
  });
}
