/**
 * The only gateway from the UI to the Rust side (enforced by ESLint, see docs/adr/0002).
 *
 * `bindings.ts` is generated by tauri-specta from the Rust command signatures; this module
 * re-exports the types and wraps each command in a function named after what it does.
 */
import {
  commands,
  LANGUAGE_MODES,
  type AppInfo,
  type CommandError,
  type ExecutionMode,
  type Language as LanguageId,
} from "./bindings";

export type { AppInfo, CommandError, ExecutionMode, LanguageId };

/** Languages and the modes each offers (default first), as defined in Rust. */
export { LANGUAGE_MODES };

/** Build information of the running application. */
export function getAppInfo(): Promise<AppInfo> {
  return commands.appInfo();
}
